server:
  port: 7006
  servlet:
    context-path: /campusParttime
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1024MB
  application:
    name: campus-parttime
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos地址
  datasource:
    druid:
      url: jdbc:mysql://117.72.15.203:3305/campus?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
      driverClassName: com.mysql.jdbc.Driver
      max-active: 100
      min-idle: 8
      initial-size: 10
    username: root
    password: olcampus8888!
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 117.72.15.203:26379
        - 117.72.14.204:26379
        - 117.72.13.205:26379
      password: olcampus8888!
    timeout: 10000
    connect-timeout: 10000
    password: olcampus8888!
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  kafka:
    bootstrap-servers: 47.115.219.35:9092
    producer:
      retries: 3 # 重新发送次数
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.parttime.domain
  configuration:
    map-underscore-to-camel-case: true


