### 模拟用户t1登录后的消息初始化(将消息写入缓存)
GET http://localhost:7002/campusMessage/message/initMessage
uid:t1

###用户1点击【首页】-【消息】
GET http://localhost:7002/campusMessage/message/clickMyMessage
uid:t1

###模拟用户t2登录后的消息初始化(将消息写入缓存)
GET http://localhost:7002/campusMessage/message/initMessage
uid:t2

### 发送好友请求
POST http://localhost:7002/campusMessage/message/send
uid:t1
Content-Type: application/json

{
  "content": "测试一下会话更新，消息发送给t2",
  "sender": "t1",
  "receiver": "t2",
  "type": 0,
  "isPhoto": false
}

<> 2023-07-25T111436.200.json

### 接受好友请求
POST http://localhost:7002/campusMessage/message/handleRequest
uid:t2
Content-Type: application/json

{
  "msgId": "1683688061020889089",
  "accept": true
}


###
GET http://localhost:7002/campusMessage/message/initMessage
uid:2

###获取2和他的好友1的聊天记录
GET http://localhost:7002/campusMessage/message/getUserChatRecords?friendId=1
uid:2


###懒加载2和他的好友1的聊天记录
GET http://localhost:7002/campusMessage/message/lazyLoadingChatRecords?friendId=1
uid:2