aliyun:
  oss:
    file:
      bucketname: edu20230513
      endpoint: oss-cn-guangzhou.aliyuncs.com
      keyid: LTAI5tDDc7oFqhiZFejDVZtp
      keysecret: UWBM3EChOz3WNt4NiiJ4N8E0dTZH00
  vod:
    file:
      keyid: LTAI5tDDc7oFqhiZFejDVZtp
      keysecret: UWBM3EChOz3WNt4NiiJ4N8E0dTZH00

server:
  port: 7005
  servlet:
    context-path: /campusOss

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
  application:
    name: campus-oss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos地址
  datasource:
    druid:
      url: jdbc:mysql://47.115.219.35:3305/campus?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
      driverClassName: com.mysql.jdbc.Driver
      max-active: 20
      min-idle: 8
      initial-size: 10
    username: root
    password: olcampus8888
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 117.72.15.203:26379
        - 117.72.14.204:26379
        - 117.72.13.205:26379
      password: olcampus8888!
    timeout: 10000
    connect-timeout: 10000
    password: olcampus8888!
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100
  kafka:
    bootstrap-servers: 47.115.219.35:9092
    producer:
      retries: 3 # 重新发送次数
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
