GET http://47.115.219.35:8888/campusUser/user/getDetail
token:eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiIxNjc2NTgxODU4MDg0MDE2MTMwIiwiZXhwIjoxNjkzOTMxODYzLCJ1c2VyIjp7ImdlbmRlciI6MCwiYXV0aCI6MCwidGVsZXBob25lIjoiMTM3NTA0NTIyODEiLCJ1cGRhdGVUaW1lIjoiMjAyMy0wNy0zMCAwNzoyMzoxMi4wIiwidXNlcklkIjoiMTY3NjU4MTg1ODA4NDAxNjEzMCIsIm9yaWdpblBhc3N3b3JkIjoiMTIzNDU2IiwicGFzc3dvcmQiOiJlMTBhZGMzOTQ5YmE1OWFiYmU1NmUwNTdmMjBmODgzZSIsImRlbGV0ZWQiOmZhbHNlLCJ1c2VySW1hZ2UiOiJodHRwczovL2VkdTIwMjMwNTEzLm9zcy1jbi1ndWFuZ3pob3UuYWxpeXVuY3MuY29tLzIwMjMvMDcvMjUvMzM4ZDk4ODMwMDkyNDUxYmJkMDBlZTJhZjIzMzI4OWIucG5nIiwiYmFsYW5jZSI6MC4wLCJjcmVhdGVUaW1lIjoiMjAyMy0wNy0wNSAyMToyMDozOS4wIiwiZ3JhZGUiOjEsImJyZWFrTnVtIjowLCJjcmVkaXQiOjAsImFjY291bnQiOiJoaGoxNzEyMTMxNTM2Iiwic3RhdHVzIjpmYWxzZSwidXNlcm5hbWUiOiJoaGoifX0.afYEZhrg5GnLLgSAnfswmEUi8r-vIj46VlFL80qXxpLnTzAsiQYnSVQtoHiM028ygP1DHF9b2CcEr-9rO6OGBg

###
POST http://47.115.219.35:8888/campusUser/login
Content-Type: application/json

{
  "loginName": "hhj1712131536",
  "password": "123456"
}


