server:
  port: 9000
spring:
  application:
    name: campus-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos地址
    gateway:
      httpclient:
        wiretap: true # 输出请求和响应的详细日志
      discovery:
        locator:
          enabled: true # 让gateway根据注册中心找到其他服务
      routes:
        - id: campus-contact   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-contact          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusContact/**
          filters:
            - Token=true
        - id: campus-recruit   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-recruit          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusRecruit/**
          filters:
            - Token=true
        - id: campus-user   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-user          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusUser/**
          filters:
            - Token=true
        - id: campus-message   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-message          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusMessage/**
          filters:
            - Token=true
        - id: campus-parttime   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-parttime          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusParttime/**
          filters:
            - Token=true

  datasource:
    druid:
      url: jdbc:mysql://47.115.219.35:3305/campus?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
      driverClassName: com.mysql.jdbc.Driver
      max-active: 20
      min-idle: 8
      initial-size: 10
    username: root
    password: olcampus8888
  redis:
    database: 1
    host: 47.115.219.35
    port: 6379
    timeout: 10000
    password: olcampus8888
  kafka:
    bootstrap-servers: 47.115.219.35:9092
    producer:
      retries: 3 # 重新发送次数
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: default-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate

mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.user.domain
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

exclude:
  patterns: # 网关非过滤路径
    - '/campusUser/login'
    - '/campusUser/register'
    - '/campusUser/send'
    - '/campusUser/user/getUserByAccount/'
    - '/campusUser/user/checkCode/'
    - '/campusUser/user/updatePassword/'
    - '/campusUser/user/checkEmailCode/'
