server:
  port: 9000
spring:
  application:
    name: campus-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos地址
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway根据注册中心找到其他服务
      routes:
        - id: campus-contact   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-contact          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusContact/**
          filters:
            - Token=true
        - id: campus-recruit   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-recruit          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusRecruit/**
          filters:
            - Token=true
        - id: campus-user   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-user          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusUser/**
          filters:
            - Token=true
        - id: campus-message   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-message          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusMessage/**
          filters:
            - Token=true
        - id: campus-parttime   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://campus-parttime          #匹配后提供服务的路由地址
          predicates:
            - Path=/campusParttime/**
          filters:
            - Token=true

  redis:
    database: 1
    host: 47.115.219.35
    port: 6379
    timeout: 10000
management:
  endpoints:
    web:
      exposure:
        include: "*"

exclude:
  patterns: # 网关非过滤路径
    - '/campusUser/login'
    - '/campusUser/register'
    - '/campusUser/send'
